### ISSUE TITLE
CPU use RKD Clockdivider

### ISSUE THREAD

**Issue by Petervos2018** [DomiKamu/Ohmer#3]
Hi Dominique, 
I love your clock divider, it's one of the best that I am using, and it works exactly the way I want it to, but my question is, could you do something about the CPU use ? It is about 4-5x as high as all the other dividers ?

![DividerCPU](https://user-images.githubusercontent.com/46076474/66344293-bc27f680-e94d-11e9-9510-d5d5e1c7aa0c.png)
Greetings Peter.

**Comment by DomiKamu** [comment]
Hi Peter,

I'm sorry for very late reply, but - due to new job - I don't have enought free time for development! and discovering your issue only this evening.

Strangely, about RKD, you're alone to report a abnormal (excessive) CPU usage, really. What platform are you using exactly (Windows-based, OSX, Linux ?) CPU ? GPU ? etc...

Also, I precise they're 8 dividers, different and variable rates, but it uses precise clock algorithms - sample-based. Some of "competitors" - at x1 - have signifiant drifts after some minutes when running, few months ago.

I'm using Intel Core i7 4790 at 3.6 GHz (Asus Maximum VII Hero mobo, 32 GB RAM), OS is Windows 7 Professional SP1 (French localized), I've never noticed 4x-5x CPU usage on my platform (and friends and other users don't have reported this, be sure I'm suprised.

Greetings, Dominique.

**Comment by Petervos2018** [comment]
No problem Dominique, just glad you're ok and I hope you like your new job.

I'm also on Windows7, and I just thought it was strange that your module had a much higher CPU usage than the other dividers.

[ClockDividers - 21122019 for Dominique.zip](https://github.com/DomiKamu/Ohmer/files/3990625/ClockDividers.-.21122019.for.Dominique.zip)

Maybe you could/would like to test my simple vcv patch and make a screenshot for me so I can see that it's just ME who is having high CPU useage with your module. 
Take your time ;) :+1: 

Greetings Peter.

**Comment by DomiKamu** [comment]
Hi Peter,

Fortunately I'll stay at home this weekend (despite I'll busy, I'm preparing my new PC - but current will stay alive for... computer music). ;)

First test I've made give (you're right), around **2.2% CPU** (screen cap) by using very basic patch: clock generator (KlokSpid), clock divider ("RKD" module, without "BRK", only input, no patched output), and unused "Audio-8" (but required anyway to avoid running x2 faster).

![Sans titre-1](https://user-images.githubusercontent.com/24851960/71304394-4d8ffc00-23c6-11ea-818e-54aacbd711aa.png)

It's not 3.4%, but 2.2% is a bit excessive (probably)... Be sure I don't understand why. Not easy to test your patch (from ZIP file) because I don't have many modules on my system:

![Sans titre-2](https://user-images.githubusercontent.com/24851960/71304467-89779100-23c7-11ea-8026-5a86df2791b3.png)

But by using existing (common) modules, the result is same:

![Sans titre-3](https://user-images.githubusercontent.com/24851960/71304490-c9d70f00-23c7-11ea-889b-524215b238ca.png)

Of course, as kind of reminder, I keep this issue open.
Thanks for this report!

Greetings from France,
Dominique Camus

**Comment by DomiKamu** [comment]
I'll contact (via Messenger) Marc Boulé, author of "Clocked" (ImpromptuModular) - perhaps he'll can help me to check my source, and to discover why we get more than 2%. It's not a memory leak (I've monitored the incomplete patch above) but _the truth is elsewhere_.

**Comment by Petervos2018** [comment]
Hi Dominique,

Sorry for giving you a vcv file with ALL the dividers in it ;) But it is/was my testing file to test which dividers do work the way I want them to. Yours is one of the 3 !

Thanks for taking the time to test this and come to a somewhat same conclusion, although your 2.2% is not my 3.4%, it is still higher than the rest.

Let's see if Marc can/will come up with an answer...

Happy Holidays to you and your family,
Peter.

**Comment by DomiKamu** [comment]
Peter, what the brand/model of CPU you're using? (mine is Intel Core i7 4790 @ 3.6 GHz stock).

I don't have checked my C++ code, also don't have touch/read the source since many months.

Don't worry about your .vcv (patch) file, I get 2.2% too, by using very basic patch, as shown above. ;)

I'll contact Marc but after holidays, I'll away (very often) from my computer. Also my new computer is planned (I hope) for February 2020 (Core i9 based, SSD and so on - assembled by myself). Already having some parts (CPU i9 9900KF, Corsair AIO watercooling, 2 TB HDD, Asus RTX 2080), but waiting (money €) for new motherboard (Asus Maximus XI Hero), DDR4 (2 x 16 GB Corsair), 480 GB SSD M.2 NVMe (Corsair), 1 TB 2.5" SATA SSD (Samsung 860 Pro)... Plus free time to reinstall all properly... :) 

Yep, many thanks Peter, and happy holidays to you and your close relatives, too!

Dominique.

**Comment by Petervos2018** [comment]
I have an Intel Core i7-2600 CPU @ 3.4GHz.
Also thinking about a new one , Windows7 also at its end... :(
(The specs  for your new one look good). :+1: 

Greetings Peter.

**Comment by DomiKamu** [comment]
Ok thanks - perhaps it's the reason why you get higher CPU usage than me. New PC will use Windows 10 Pro (instead of Windows 7 Pro SP1).

Specs for new one seems good, but as long as I don't have all parts... To be honest, the PC upgrade wasn't required, since I've replaced the GTX 660 2GB by RTX 2080 8GB), but assuming 1/ it's my Christmas gift lol (every X-mas since 2012, I buy a VSTi plugin such synth - previous 2018 was VPS Avenger, 2017 was u-he Diva, 2016 was Synapse's DUNE 2, and so on) 2/ to be consistent between CPU and new GPU (I'm a bit gamer too)...

**Comment by DomiKamu** [comment]
Hi again, Peter, Marc have replied and given some interestings tips for optimizations (to reduce CPU loads). Mine modules are working every frame, but it's not necessary for displays & LEDs (for example). I don't plan an update of Ohmer modules yet (not prior February 2020) but it goes UNDER CONSIDERATION ! ;) but they're many stuffs on this module...

**Comment by Petervos2018** [comment]
Cool :+1: take your time :)

Thanks for everything so far,
Peter.

**Comment by DomiKamu** [comment]
Hi Peter, good news, having my new PC, having reinstalled Rack 1.1.6 + developer... Now I'll try to take times to update RKD module! ;)

**Comment by DomiKamu** [comment]
The issue now is fixed by addressing all (8) displays (when CLK is wired) every 32 frames (samples). Now CPU load can't exceed 0.1%.

The Windows binary is available from "Releases" - please use v1.1.6. Thanks!
(coming in couple of days in VCV Plugin Library).
Issue closed.

**Comment by Petervos2018** [comment]
Thank you this works great 👍
